### PR TITLE
Fix PDF generation with superadmin that has no profile

### PR DESCRIPTION
**Pull request by casaper**
…t any profile

# [Story in Trello](https://trello.com/c/GHZeQZhk/49-check-after-deploy-exception-on-staging-when-creating-pdf)

### Done for approval?

* [x] Acceptance criteria are met
* [x] Code quality checks are green
* [ ] ~Readme updated if needed~
* [x] Story under test
* [ ] ~Mobile works~
* [ ] ~Seeds created~
* [ ] ~Translated~
* [x] Code is reviewed

### Done after the merge?

* [ ] Deployed to staging after the merge
* [ ] Tested manually on staging

### CODE REVIEW

**Comment by casaper** [comment]
@chrysalag 
But a user not having a profile at all, isn't it a edge case?
And If there'd be a profile with contact in it that has blank first_name and lastname etc. fields, this part of the template will still be run?

**Comment by chrysalag** [comment]
@casaper It is indeed an edge case. But if it can happen, what I would suggest is that the fields for completion appear in all cases and they are filled out in case they have a value.

**Comment by casaper** [comment]
@chrysalag I would rather suggest to fix that it can happen, so that this will only be a worst case catch

**Comment by casaper** [comment]
@toupeira agreee. I'm glad to make one...

**Pull request merged**
